### ISSUE TITLE
xk6-playright stucks on execution 

### ISSUE THREAD

**Issue by romic-azure** [wosp-io/xk6-playwright#14]
Hello,
Tried to install according to the Readme.md and tried to run the first script - **simplest-working-example.js**, started running and got stuck.

![kx6_playwright](https://github.com/wosp-io/xk6-playwright/assets/115095145/b553841e-74a0-4fc3-8a61-8427829629b6)

**Comment by nicholasvuono** [comment]
Hello 👋🏻 sorry to hear it's getting stuck! Are you trying to run this on Windows, Linux, or Mac?

**Comment by nicholasvuono** [comment]
@romic-azure this was due to selector changes for the examples, causing them to fail. I have updated the examples to include what k6 has set up for a dedicated testing site so now the tests should be less flaky and more future proof. In addition, I have also update a new release with a few dependency changes so please go back through and follwo the steps to rebuildthe executable. 

If the issue still persists feel free to open up another issue! 

I appreciate the feedback with this it was very helpful and should help others tryign to use the tool in the future 🙏🏻

**Comment by romic-azure** [comment]
Hello,
sorry, been a bit busy. 
yes, it was on Windows.
will give it a try and let you know.
thanks for the quick reply!

**Comment by nicholasvuono** [comment]
hey, no worries! hopefully it's working better for you 🙏🏻
